[package]
name = "waterkit-secret"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Cross-platform Secure storage and keychain management"
keywords = ["secret", "keychain", "password", "security", "credentials"]
categories = ["os", "gui"]

[lints]
workspace = true

[dependencies]
thiserror.workspace = true

# Apple (iOS, macOS)
[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["apple-native"] }

# Android
[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
ndk-context.workspace = true

# Windows
[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["windows-native"] }

# Linux
[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3.6.3", default-features = false, features = ["linux-native"] }
