[package]
name = "waterkit-share"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Cross-platform share sheet and social sharing"
keywords = ["share", "sharing", "social", "send"]
categories = ["os", "gui"]

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
percent-encoding = { workspace = true }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc2.workspace = true
waterkit-core.workspace = true
objc2-foundation = { workspace = true, features = [
    "NSArray",
    "NSError",
    "NSGeometry",
    "NSObject",
    "NSString",
    "NSURL",
] }

[target.'cfg(target_os = "ios")'.dependencies]
block2.workspace = true
objc2-foundation = { workspace = true, features = [
    "NSKeyValueCoding",
    "NSSet",
] }
objc2-ui-kit = { workspace = true, features = [
    "UIActivityViewController",
    "UIActivity",
    "UIApplication",
    "UIImage",
    "UIResponder",
    "UIScene",
    "UISceneDefinitions",
    "UIView",
    "UIViewController",
    "UIWindowScene",
    "UIWindow",
    "block2",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { workspace = true, features = [
    "NSApplication",
    "NSImage",
    "NSResponder",
    "NSSharingService",
    "NSView",
    "NSWindow",
] }

[target.'cfg(target_os = "android")'.dependencies]
waterkit-build.workspace = true
jni.workspace = true
ndk-context.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "ApplicationModel_DataTransfer",
    "Foundation",
    "Storage",
    "Storage_Streams",
] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus.workspace = true
