[package]
name = "waterkit-deeplink"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Cross-platform deep linking and URL scheme handling"
keywords = ["deeplink", "url-scheme", "universal-links"]
categories = ["os", "web-programming"]

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
futures-core = "0.3"
async-channel = { workspace = true }
url = { workspace = true }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc2.workspace = true
waterkit-core.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
block2.workspace = true
objc2-foundation = { workspace = true, features = [
    "NSDictionary",
    "NSNotification",
    "NSOperation",
    "NSString",
    "NSURL",
] }
objc2-ui-kit = { workspace = true, features = [
    "UIApplication",
    "UIResponder",
    "UIScene",
    "block2",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { workspace = true, features = ["NSWorkspace"] }
objc2-core-services = { workspace = true, features = ["AEDataModel", "AppleEvents"] }
objc2-foundation = { workspace = true, features = [
    "NSAppleEventDescriptor",
    "NSAppleEventManager",
    "NSObject",
    "NSString",
    "NSURL",
    "objc2-core-services",
] }

[target.'cfg(target_os = "android")'.dependencies]
waterkit-build.workspace = true
jni.workspace = true
ndk-context.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Foundation", "System"] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus.workspace = true


