[package]
name = "waterkit-calendar"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Cross-platform calendar and events access"
keywords = ["calendar", "events", "schedule"]
categories = ["os"]

[lints]
workspace = true

[dependencies]
waterkit-core = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
blocking = { workspace = true }
serde = { workspace = true }
jiff = { workspace = true, features = ["serde"] }
waterkit-fs = { workspace = true }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
swift-bridge.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
ndk-context.workspace = true

[build-dependencies]
waterkit-build.workspace = true
