[package]
name = "waterkit-bluetooth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Cross-platform Bluetooth (BLE and Classic)"
keywords = ["bluetooth", "ble", "wireless"]
categories = ["os", "hardware-support"]

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
async-channel = { workspace = true }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
swift-bridge.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
ndk-context.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Devices_Bluetooth",
    "Devices_Bluetooth_GenericAttributeProfile",
    "Devices_Bluetooth_Advertisement",
    "Devices_Bluetooth_Rfcomm",
    "Devices_Enumeration",
    "Devices_Radios",
    "Foundation",
    "Foundation_Collections",
    "Networking",
    "Networking_Sockets",
    "Storage_Streams",
] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
zbus.workspace = true

[build-dependencies]
waterkit-build.workspace = true
