[package]
name = "waterkit-video"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Video playback and processing"
keywords = ["video", "playback", "mp4", "mov", "hardware"]
categories = ["multimedia::video", "gui"]

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
wgpu.workspace = true
futures.workspace = true
async-channel.workspace = true

# MP4/MOV container support
byteorder = { workspace = true }
mp4 = { workspace = true }

# Hardware codec support
waterkit-codec = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
