[package]
name = "waterkit-camera-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
waterkit-camera.workspace = true
winit.workspace = true
wgpu.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
futures.workspace = true
async-channel.workspace = true
env_logger = "0.11"
