use std::{
    future::Future,
    num::NonZeroUsize,
    pin::Pin,
    str::FromStr as _,
    sync::Arc,
    time::{Duration, Instant},
};

use bytes::Bytes;
use url::Url;
use waterkit_video_core::Error;
use zenwave::{
    Method, ResponseExt as _,
    header::{HeaderMap, HeaderName, HeaderValue},
};

use crate::transport::{TransportRequest, send};

/// One platform-CDM license challenge and its bounded network policy.
#[derive(Debug, Clone)]
pub struct LicenseRequest {
    system_id: [u8; 16],
    url: Url,
    challenge: Vec<u8>,
    headers: HeaderMap,
    maximum_response_bytes: NonZeroUsize,
    maximum_redirects: u8,
    forward_cross_origin_credentials: bool,
}

impl LicenseRequest {
    /// Creates a validated raw license challenge.
    ///
    /// # Errors
    ///
    /// Returns an error when the challenge is empty or the URL is not HTTP(S).
    pub fn new(
        system_id: [u8; 16],
        url: Url,
        challenge: Vec<u8>,
        maximum_response_bytes: NonZeroUsize,
    ) -> Result<Self, Error> {
        if challenge.is_empty() {
            return Err(Error::Streaming(String::from(
                "platform CDM produced an empty license challenge",
            )));
        }
        if !matches!(url.scheme(), "http" | "https") {
            return Err(Error::Streaming(format!(
                "license URL must use HTTP or HTTPS, got {}",
                url.scheme()
            )));
        }
        Ok(Self {
            system_id,
            url,
            challenge,
            headers: HeaderMap::new(),
            maximum_response_bytes,
            maximum_redirects: 10,
            forward_cross_origin_credentials: false,
        })
    }

    /// Adds one validated request header.
    ///
    /// # Errors
    ///
    /// Returns an error when the name or value is not a valid HTTP header.
    pub fn with_header(mut self, name: &str, value: &str) -> Result<Self, Error> {
        let name = HeaderName::from_str(name)
            .map_err(|error| Error::Streaming(format!("invalid license header name: {error}")))?;
        let value = HeaderValue::from_str(value)
            .map_err(|error| Error::Streaming(format!("invalid license header value: {error}")))?;
        self.headers.insert(name, value);
        Ok(self)
    }

    /// Changes the maximum number of redirects followed by the request.
    #[must_use]
    pub const fn with_maximum_redirects(mut self, maximum_redirects: u8) -> Self {
        self.maximum_redirects = maximum_redirects;
        self
    }

    /// Explicitly permits credential headers to cross origin boundaries.
    ///
    /// This is disabled by default. Scheme, host, and port all participate in
    /// the origin comparison.
    #[must_use]
    pub const fn with_cross_origin_credentials(mut self, enabled: bool) -> Self {
        self.forward_cross_origin_credentials = enabled;
        self
    }

    /// Returns the DRM system UUID in network byte order.
    #[must_use]
    pub const fn system_id(&self) -> &[u8; 16] {
        &self.system_id
    }

    /// Returns the license endpoint.
    #[must_use]
    pub const fn url(&self) -> &Url {
        &self.url
    }

    /// Returns the opaque challenge generated by the platform CDM.
    #[must_use]
    pub fn challenge(&self) -> &[u8] {
        &self.challenge
    }

    /// Returns the maximum accepted response size.
    #[must_use]
    pub const fn maximum_response_bytes(&self) -> NonZeroUsize {
        self.maximum_response_bytes
    }
}

/// Opaque license bytes returned to a platform CDM.
#[derive(Debug, Clone)]
pub struct LicenseResponse {
    effective_url: Url,
    bytes: Bytes,
    elapsed: Duration,
}

impl LicenseResponse {
    /// Creates a non-empty license response.
    ///
    /// # Errors
    ///
    /// Returns an error when `bytes` is empty.
    pub fn new(
        effective_url: Url,
        bytes: impl Into<Bytes>,
        elapsed: Duration,
    ) -> Result<Self, Error> {
        let bytes = bytes.into();
        if bytes.is_empty() {
            return Err(Error::Streaming(String::from(
                "license server returned an empty response",
            )));
        }
        Ok(Self {
            effective_url,
            bytes,
            elapsed,
        })
    }

    /// Returns the final URL after redirects.
    #[must_use]
    pub const fn effective_url(&self) -> &Url {
        &self.effective_url
    }

    /// Returns the opaque license bytes supplied to the platform CDM.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Consumes this response and returns the opaque license bytes.
    #[must_use]
    pub fn into_bytes(self) -> Bytes {
        self.bytes
    }

    /// Returns the complete HTTP exchange duration.
    #[must_use]
    pub const fn elapsed(&self) -> Duration {
        self.elapsed
    }
}

/// Acquires licenses for opaque challenges generated by a platform CDM.
pub trait LicenseServer: Send + Sync + 'static {
    /// Performs one license exchange.
    fn acquire(
        &self,
        request: LicenseRequest,
    ) -> impl Future<Output = Result<LicenseResponse, Error>> + Send;
}

trait LicenseServerImpl: Send + Sync {
    fn acquire_boxed(
        &self,
        request: LicenseRequest,
    ) -> Pin<Box<dyn Future<Output = Result<LicenseResponse, Error>> + Send + '_>>;
}

impl<T: LicenseServer> LicenseServerImpl for T {
    fn acquire_boxed(
        &self,
        request: LicenseRequest,
    ) -> Pin<Box<dyn Future<Output = Result<LicenseResponse, Error>> + Send + '_>> {
        Box::pin(self.acquire(request))
    }
}

/// Type-erased license server for platform playback coordinators.
#[derive(Clone)]
pub struct AnyLicenseServer {
    inner: Arc<dyn LicenseServerImpl>,
}

impl AnyLicenseServer {
    /// Erases a concrete license server without weakening its public trait API.
    #[must_use]
    pub fn new(server: impl LicenseServer) -> Self {
        Self {
            inner: Arc::new(server),
        }
    }
}

impl std::fmt::Debug for AnyLicenseServer {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("AnyLicenseServer")
            .finish_non_exhaustive()
    }
}

impl LicenseServer for AnyLicenseServer {
    async fn acquire(&self, request: LicenseRequest) -> Result<LicenseResponse, Error> {
        self.inner.acquire_boxed(request).await
    }
}

/// Raw challenge/response license server implemented exclusively with Zenwave.
#[derive(Debug, Clone, Copy, Default)]
pub struct ZenwaveLicenseServer;

impl LicenseServer for ZenwaveLicenseServer {
    async fn acquire(&self, request: LicenseRequest) -> Result<LicenseResponse, Error> {
        let started = Instant::now();
        let (effective_url, response) = send(TransportRequest {
            method: Method::POST,
            url: &request.url,
            headers: &request.headers,
            body: Some(&request.challenge),
            maximum_redirects: request.maximum_redirects,
            forward_cross_origin_credentials: request.forward_cross_origin_credentials,
        })
        .await?;
        let status = response.status();
        let bytes = response
            .into_bytes_with_limit(request.maximum_response_bytes.get())
            .await
            .map_err(|error| Error::Streaming(format!("license response failed: {error}")))?;
        if !status.is_success() {
            let detail = String::from_utf8_lossy(&bytes);
            return Err(Error::Streaming(format!(
                "POST {effective_url} returned HTTP {status}: {detail}"
            )));
        }
        LicenseResponse::new(effective_url, bytes, started.elapsed())
    }
}

/// Sends a raw platform-CDM challenge through [`ZenwaveLicenseServer`].
///
/// # Errors
///
/// Returns a streaming error for transport, redirect, response-size, status,
/// or empty-response failures.
pub async fn acquire_license(request: LicenseRequest) -> Result<LicenseResponse, Error> {
    ZenwaveLicenseServer.acquire(request).await
}

#[cfg(test)]
mod tests {
    use std::{
        io::{Read as _, Write as _},
        net::TcpListener,
        num::NonZeroUsize,
        thread,
    };

    use super::{LicenseRequest, acquire_license};
    use crate::Url;

    #[test]
    fn raw_license_exchange_posts_challenge_and_returns_bounded_response() {
        let server = TcpListener::bind(("127.0.0.1", 0)).expect("test server must bind");
        let address = server.local_addr().expect("test server address must exist");
        let worker = thread::spawn(move || {
            let (mut socket, _) = server.accept().expect("license request must arrive");
            let (headers, body) = read_request(&mut socket);
            assert!(headers.starts_with("POST /license HTTP/1.1"));
            assert!(
                headers
                    .to_ascii_lowercase()
                    .contains("x-license-token: token")
            );
            assert_eq!(body, b"cdm-challenge");
            socket
                .write_all(
                    b"HTTP/1.1 200 OK\r\nContent-Length: 15\r\nConnection: close\r\n\r\nlicense-payload",
                )
                .expect("license response must write");
        });
        let request = LicenseRequest::new(
            [7; 16],
            Url::parse(&format!("http://{address}/license")).expect("test URL must parse"),
            b"cdm-challenge".to_vec(),
            NonZeroUsize::new(15).expect("response bound must be non-zero"),
        )
        .expect("license request must be valid")
        .with_header("x-license-token", "token")
        .expect("license header must be valid");
        let response = futures::executor::block_on(acquire_license(request))
            .expect("license exchange must succeed");
        assert_eq!(response.bytes(), b"license-payload");
        worker.join().expect("license server must finish");
    }

    fn read_request(socket: &mut std::net::TcpStream) -> (String, Vec<u8>) {
        let mut bytes = Vec::new();
        let header_end = loop {
            let mut chunk = [0_u8; 1_024];
            let read = socket.read(&mut chunk).expect("request must read");
            assert_ne!(read, 0, "request ended before its headers");
            bytes.extend_from_slice(&chunk[..read]);
            if let Some(position) = bytes.windows(4).position(|part| part == b"\r\n\r\n") {
                break position + 4;
            }
            assert!(bytes.len() < 16_384, "request headers exceeded test bound");
        };
        let headers =
            String::from_utf8(bytes[..header_end].to_vec()).expect("request headers must be UTF-8");
        let content_length = headers
            .lines()
            .find_map(|line| {
                let (name, value) = line.split_once(':')?;
                name.eq_ignore_ascii_case("content-length").then(|| {
                    value
                        .trim()
                        .parse::<usize>()
                        .expect("content length must parse")
                })
            })
            .expect("license request must declare Content-Length");
        while bytes.len() - header_end < content_length {
            let mut chunk = [0_u8; 1_024];
            let read = socket.read(&mut chunk).expect("request body must read");
            assert_ne!(read, 0, "request ended before its body");
            bytes.extend_from_slice(&chunk[..read]);
        }
        (
            headers,
            bytes[header_end..header_end + content_length].to_vec(),
        )
    }
}
