[package]
name = "waterkit-test-ios"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[package.metadata.cargo-machete]
ignored = ["waterkit"]

[dependencies]
swift-bridge.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
waterkit = { path = "../../..", default-features = false }
waterkit-test-report.workspace = true

[features]
sensor = ["waterkit/sensor"]
biometric = ["waterkit/biometric"]
location = ["waterkit/location"]
audio = ["waterkit/audio"]
camera = ["waterkit/camera"]
clipboard = ["waterkit/clipboard"]
codec = ["waterkit/codec"]
dialog = ["waterkit/dialog"]
fs = ["waterkit/fs"]
haptic = ["waterkit/haptic"]
notification = ["waterkit/notification"]
permission = ["waterkit/permission"]
secret = ["waterkit/secret"]
system = ["waterkit/system"]
video = ["waterkit/video"]
screen = ["waterkit/screen"]
bluetooth = ["waterkit/bluetooth"]
nfc = ["waterkit/nfc"]
share = ["waterkit/share"]
speech = ["waterkit/speech"]
contacts = ["waterkit/contacts"]
calendar = ["waterkit/calendar"]
health = ["waterkit/health"]
deeplink = ["waterkit/deeplink"]
background = ["waterkit/background"]
passkey = ["waterkit/passkey"]

[build-dependencies]
swift-bridge-build.workspace = true
waterkit-build.workspace = true
