[package]
name = "waterkit-speech"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Cross-platform text-to-speech and speech recognition"
keywords = ["tts", "speech", "voice", "recognition"]
categories = ["multimedia::audio", "accessibility"]

[lints]
workspace = true

[dependencies]
waterkit-core = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
futures-core = "0.3"
async-channel = { workspace = true }
futures-timer = { workspace = true }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
swift-bridge.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
waterkit-build.workspace = true
jni.workspace = true
ndk-context.workspace = true
tokio = { workspace = true, features = ["sync", "macros"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Media_SpeechSynthesis",
    "Media_SpeechRecognition",
    "Media_Core",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams",
    "Globalization",
] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus.workspace = true
async-process.workspace = true

[build-dependencies]
waterkit-build.workspace = true
