name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-hosted:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install dav1d nasm ffmpeg
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install pkgconfiglite -y
          vcpkg install dav1d:x64-windows
        env:
          VCPKG_ROOT: C:\vcpkg
      - name: Set Windows pkg-config paths
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "PKG_CONFIG_PATH=C:/vcpkg/installed/x64-windows/lib/pkgconfig" >> $GITHUB_ENV
          echo "C:/vcpkg/installed/x64-windows/bin" >> $GITHUB_PATH
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ matrix.os }}
      - run: cargo test --verbose --all-features

  test-linux:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:full-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-ubuntu-latest
      - run: cargo test --verbose --all-features
